HOFF-642-Update UKVI EoT to HOF v20.4.0
UKHomeOffice/end-tenancy pull request #218
Opened 2024-03-05 13:48 UTC by TemitopeAyokuHO

## What?
[HOFF-642 ](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-642).- changing Queen's crown to King's crown logo
 
## Why?
The Gov.uk crown logo changed
 
## How?
npm install hof@20.4.0
 
## Testing?
Tested locally
 
## Screenshots (optional)
 
![Screenshot 2024-02-29 at 17 09 10](https://github.com/UKHomeOffice/end-tenancy/assets/138882912/fc46e804-7be5-4e4c-86b2-d86c299a1344)

2024-03-05 23:53 UTC, Rhodine-orleans-lindsay requested changes

2024-03-05 23:53 UTC, Rhodine-orleans-lindsay commented on package-lock.json
Please delete this file - we use yarn.lock so don't need package-lock.json(it was probably created by running ``npm install``` instead of ```yarn install```). ICan you also update the readme so that the install and run instructions use yarn instead of npm to avoid confusion?

2024-03-06 09:23 UTC, TemitopeAyokuHO commented on package-lock.json
done

2024-03-06 09:40 UTC, Rhodine-orleans-lindsay commented on package-lock.json
It doesn't look like the readme has been updated

2024-03-06 10:49 UTC, Rhodine-orleans-lindsay requested changes

2024-03-06 10:49 UTC, Rhodine-orleans-lindsay commented on package-lock.json
Can you also change ```npm run dev``` to ```yarn run dev```?

2024-03-06 10:50 UTC, Rhodine-orleans-lindsay requested changes

2024-03-06 10:50 UTC, Rhodine-orleans-lindsay commented on README.md
Can you also change ```npm run dev``` to ```yarn run dev?```

2024-03-06 10:50 UTC, TemitopeAyokuHO commented on package-lock.json
done, can you please check again

2024-03-06 10:53 UTC, TemitopeAyokuHO commented on README.md
done

2024-03-06 12:21 UTC, Rhodine-orleans-lindsay approved these changes
lgtm

2024-03-11 20:35 UTC, merged